### ISSUE TITLE
List dependents

### ISSUE THREAD

**Issue by jrburke** [amodrojs/amodro-trace#4]
This is a follow on from #3: it can be useful to see what modules directly depend on a particular module, related to the entry related to that particular module ID. So something like this:

``` json
    {
      "id": "b",
      "path": "/full/path/to/b.js",
      "contents": "define({\n  name: 'b'\n});\n",
      "dependents": [
        "a"
      ]
    },
    {
      "id": "a",
      "path": "/full/path/to/a.js",
      "contents": "define(['b'], function(b) { return { name: 'a', b: b }; });",
      "deps": [
        "b"
      ],
      "dependents": [
        "main"
      ]
    },
    {
      "id": "main",
      "path": "/full/path/to/main.js",
      "contents": "require(['a'], function(a) {});",
      "deps": [
        "a"
      ]
    }
```

Make sure to include it for `otherIds` too.

**Comment by jrburke** [comment]
Not sure yet if this should be a config option. Leaning towards not having a config option. It increases the size of the output, but as far as processing it is not too much extra.

**Comment by prantlf** [comment]
Thanks for this!  "dependents" are much better, than "parent" what I showed in #3.  I upgraded to you latest release, adapted my code to deps and dependents and it works great!

I use amodro-trace to analyze bundle content and check, if all shared modules are listed in bundle indexes and the bundles are distinct.

**Comment by jrburke** [comment]
Glad to hear it worked out!
