### ISSUE TITLE
update esprima dependency

### ISSUE THREAD

**Issue by 5ebastianMeier** [amodrojs/amodro-trace#9]
Hey, I was just wandering if you could update to esprima@4 in the near future - it seems to me that there are no really big changes in terms of API compatibility, but that release supports full ES2016 (including async/await which I'm after ;)

The aurelia-cli uses your module and I noticed that updating to esprima@4 seems to solve the issue - otherwise any `async` keyword will result in an `Unexpected identifier`.

**Comment by jrburke** [comment]
Published in version 1.0.1.
